### ISSUE TITLE
rgb_to_cmyk doesn't work

### ISSUE THREAD

**Issue by LJTDiSZ** [jpederson/node-colorvert#1]
cvert.rgb_to_cmyk(223, 0, 41, function(err, cmyk){
        console.log(cmyk);
        res.write(JSON.stringify(cmyk));
});

I got an error saying,

node_modules/colorvert/rgb/cmyk.js:18
            "c": Math.round( cmyk[0] ),
                                 ^
TypeError: Cannot read property '0' of undefined

**Comment by jpederson** [comment]
This was fixed in a subsequent release - super delayed response, my apologies..
